---
title: "Importación/exportación de datos espaciales con R"
output: html_notebook
---
### Importación de archivos shape

```{r}
# Carga el paquete sf
library(sf)

# Determina la ruta del espacio de trabajo  CAMBIAR A SU CARPETA!!
# En windows sería algo tipo setwd("C:/Users/xx/libro_SIG/datos-mx")
setwd("~/Documents/workspace-r/recursos-mx")
mx <- st_read("Entidades_latlong.shp")
# Pregunta la clase del objeto espacial
class(mx) # Es un simple feature "sf"
summary(mx) # un dataframe con una columna "lista" sobre la geometría
# plotea el mapa (um mapa para cada atributo)
plot(mx, axes = T,cex.axis=0.8) #cex.axis controla tamaño coordenadas
# Para plotear únicamente la geometría
plot(st_geometry(mx))

# Pregunta por el sistema de proyección
st_geometry(mx)  # equivalente a print(mx$geometry)
st_crs(mx) # por código EPSG y proj4string

carr <- st_read("carretera.shp")
st_crs(carr) # No hay información sobre el sistema de coordenadas
# se define:
st_crs(carr) <- "+proj=lcc +lat_1=17.5 +lat_2=29.5 +lat_0=12 +lon_0=-102
                 +x_0=2500000 +y_0=0 +ellps=GRS80 +units=m +no_defs"
# Test de la validez de los mapas
st_is_valid(mx)
```
### Importación de archivos vector de otros formatos

```{r}
drivers_soportados <- st_drivers()
names(drivers_soportados)
# Lista de los 10 primeros drivers de la lista (hay más!)
head(drivers_soportados[,-2], n = 10)
```

**En general, st_read() determina cual driver debe utilizar con base en la extensión del archivo.**

### Exportación a shape o a otros formatos

```{r}
# Salva el objeto en formato shape
st_write(mx,"mexico.shp",delete_layer = TRUE)
st_write(mx, dsn = "mx.gpkg", delete_layer = TRUE)
```

**Con sp:**

```{r}
library(sp)
mx_sp <- as(mx, Class = "Spatial")
# Regreso a sf con st_as_sf():
mx_sf <- st_as_sf(mx_sp, "sf")
```

### Importación / exportación de datos raster

```{r}
library(raster)
# Importa imagen
dem <- raster("~/Documents/workspace-r/recursos-mx/DEM_GTOPO1KM.tif")
class(dem)
plot(dem)
extent(dem)
# Formatos disponibles para salvar
writeFormats()
# Salva el raster en formato LAN
writeRaster(dem, filename="DEM_Mx.lan", format="LAN", overwrite=TRUE,
            datatype="INT2S")
````